### model
model_name_or_path: path/LLaMA-Factory/model/Qwen2-7B-Instruct-bnb-4bit
quantization_bit: 4

### method
stage: rm
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj


### dataset
dataset: legal_dataset
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/unsloth-qwen2-7b/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
